modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"


issueTrackerURL="https://github.com/Bluemethyst/ScytheJS/issues"

[[mods]]
modId = "scythejs"
version = "0.0.1-1.20.1"
displayName = "ScytheJS"
credits="Thanks to FooterMan for the KubeJS Addon Template! And making this mod possible!"
authors="Bluemethyst"
description = '''
ScytheJS, addon for KubeJS for adding scythes. Thats it.
'''

[[dependencies.scythejs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scythejs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scythejs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
